# Generated by Django 4.0.4 on 2022-06-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_name', models.CharField(max_length=50)),
                ('neighbourhood_location', models.CharField(max_length=60)),
                ('neighbourhood_hood_logo', models.ImageField(upload_to='images/')),
                ('neighbourhood_description', models.TextField()),
                ('neighbourhood_health_tell', models.IntegerField(blank=True, null=True)),
                ('neighbourhood_police_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(default='default.png', upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_email', models.EmailField(blank=True, max_length=254)),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='mtaani.neighbourhood')),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=255)),
                ('post_description', models.TextField(max_length=255)),
                ('post_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtaani.business')),
                ('post_neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtaani.neighbourhood')),
                ('post_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtaani.profile')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='mtaani.profile'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='mtaani.neighbourhood'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mtaani.profile'),
        ),
    ]
