# Generated by Django 4.0.4 on 2022-06-20 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtaani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='mtaani.neighbourhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mtaani.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_neighbourhood', to='mtaani.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_health_tell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_hood_logo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_location',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_police_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaani.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_neighbourhood', to='mtaani.neighbourhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='mtaani.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='mtaani.neighbourhood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_tell',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
