# Generated by Django 4.0.4 on 2022-06-19 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtaani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_neighbourhood', to='mtaani.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='mtaani.profile'),
        ),
    ]
