# Generated by Django 4.0.4 on 2022-06-18 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtaani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_location', to='mtaani.neighbourhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hospital_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='nameof_neighbour',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_by_business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaani.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaani.neighbourhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaani.profile'),
            preserve_default=False,
        ),
    ]
