# Generated by Django 4.0.4 on 2022-06-20 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtaani', '0002_business_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_neighbourhood', to=settings.AUTH_USER_MODEL),
        ),
    ]
