# Generated by Django 4.0.4 on 2022-06-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtaani', '0002_business_business_location_business_business_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_by_business',
            new_name='post_business',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='post_description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='profile',
            new_name='post_profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='post_user',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_location',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_owner',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='hospital_number',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='nameof_neighbour',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='police_line',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='business',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='mtaani.neighbourhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mtaani.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='mtaani.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_tell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_logo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='mtaani.neighbourhood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
