# Generated by Django 4.0.4 on 2022-06-20 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtaani', '0004_remove_profile_location_remove_profile_neighbourhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_tell',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
